### ISSUE TITLE
Not working on MBP 15 late 2013

### ISSUE THREAD

**Issue by Neve** [ianmaddox/MacSaber#1]
Debug:
Version: 1.1
SMS Error: -2
MacBookPro11,3
Class: 4

Found nothin on google regarding this issue, so sending it here

**Comment by ianmaddox** [comment]
Sorry, Macsaber doesn't work with SSD equipped computers. It relied on a gyro sensor equipped to park the head of a spinning dosk drive if you dropped the computer.
